services:
  # Backend service
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: GymManager.settings
    volumes:
      - ./backend:/usr/src/app
    command: ["watchmedo", "auto-restart", "--patterns=*.py", "--recursive", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - frontend

  # Frontend service
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    working_dir: /frontend
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true