name: Build and Deploy Python App to Azure Web App - Development Environment

on:
  push:
    branches:
      - develop  # Trigger on pushes to the 'develop' branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt  # Ensure the requirements.txt path is correct

      # Create a ZIP package of the application for deployment
      - name: Create ZIP package
        run: |
          cd backend  # Navigate into the backend directory
          zip -r ../app.zip . -x "*.git*" -x "*venv*"  # Create app.zip at the root
          
      # Debugging step to check if app.zip is present
      - name: List files for debugging
        run: ls -la

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: app.zip
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App - Development'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'unifiedgymmanager'  # Name of the Azure Web App
          package: './app.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND_DEV }}
