name: Build and Deploy Dockerized App to Azure Web App - Development Environment

on:
  push:
    branches:
      - develop  # Trigger on pushes to the 'develop' branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx for building Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub or Azure Container Registry (if using a private registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t unifiedgymmanager-backend-dev ./backend
          docker tag unifiedgymmanager-backend-dev:latest ${{ secrets.DOCKER_USERNAME }}/unifiedgymmanager-backend-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/unifiedgymmanager-backend-dev:latest

      # Build and push the frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t unifiedgymmanager-frontend-dev ./frontend
          docker tag unifiedgymmanager-frontend-dev:latest ${{ secrets.DOCKER_USERNAME }}/unifiedgymmanager-frontend-dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/unifiedgymmanager-frontend-dev:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      # Log in to Docker Hub or Azure Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Deploy to Azure Web App (for Containers)
      - name: 'Deploy backend to Azure Web App - Development'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'unifiedgymmanager-backend-dev'  # Name of the Azure Web App for the backend (development)
          images: '${{ secrets.DOCKER_USERNAME }}/unifiedgymmanager-backend-dev:latest'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND_DEV }}

      - name: 'Deploy frontend to Azure Web App - Development'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'unifiedgymmanager-frontend-dev'  # Name of the Azure Web App for the frontend (development)
          images: '${{ secrets.DOCKER_USERNAME }}/unifiedgymmanager-frontend-dev:latest'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND_DEV }}
